#!/bin/sh

set -eu

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
CHECKPOINT_ROOT=$(CDPATH= cd -- "$REPO_ROOT/../../../checkpoints" && pwd)
BASE_MODEL_DIR="$CHECKPOINT_ROOT/Cosmos-Predict2-2B-Video2World"
POLICY_MODEL_DIR="$CHECKPOINT_ROOT/Cosmos-Policy-LIBERO-Predict2-2B"
POLICY_CKPT_PATH=${SMOKE_POLICY_CKPT_PATH:-$POLICY_MODEL_DIR/Cosmos-Policy-LIBERO-Predict2-2B.pt}
HF_REPO_DIR="$CHECKPOINT_ROOT/huggingface-hub/models--nvidia--Cosmos-Predict2-2B-Video2World"
HF_REVISION="f50c09f5d8ab133a90cac3f4886a6471e9ba3f18"

GPU_ID=${GPU_ID:-7}
SMOKE_GL_BACKEND=${SMOKE_GL_BACKEND:-egl}
SMOKE_SUITE=${SMOKE_SUITE:-libero_spatial}
SMOKE_TASK_ID=${SMOKE_TASK_ID:-0}
FLIP_IMAGES=${FLIP_IMAGES:-true}
SMOKE_SEED=${SMOKE_SEED:-7}
SMOKE_DETERMINISTIC_RESET=${SMOKE_DETERMINISTIC_RESET:-true}
SMOKE_DETERMINISTIC_RESET_SEED=${SMOKE_DETERMINISTIC_RESET_SEED:-0}
SMOKE_MODE=${SMOKE_MODE:-paired}
SMOKE_ONLY_CONDITION=${SMOKE_ONLY_CONDITION:-both}
SMOKE_NUM_PAIRS=${SMOKE_NUM_PAIRS:-20}
SMOKE_RESULTS_DIR=${SMOKE_RESULTS_DIR:-./experiments/paired_smoke_vla_jepa_kitchen_scene4_seed7_20case}
SMOKE_RUN_ID=${SMOKE_RUN_ID:-vla_jepa_kitchen_scene4_seed7_20case}
SMOKE_QUIET_STEP_LOGS=${SMOKE_QUIET_STEP_LOGS:-true}
SMOKE_PROMPT_OVERRIDE=${SMOKE_PROMPT_OVERRIDE:-}

# VLA-JEPA LIBERO-plus task used for paired clean/perturb diagnostics.
SMOKE_PAIR_SUITE=${SMOKE_PAIR_SUITE:-libero_10}
SMOKE_PAIR_BASE_TASK=${SMOKE_PAIR_BASE_TASK:-KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it}
SMOKE_PAIR_CLEAN_LANGUAGE=${SMOKE_PAIR_CLEAN_LANGUAGE:-put the black bowl in the bottom drawer of the cabinet and close it}
SMOKE_PAIR_PERT_NAME=${SMOKE_PAIR_PERT_NAME:-camera_viewpoints,background_textures,light_conditions,objects_layout,robot_initial_states,sensor_noise}
SMOKE_PAIR_PERT_CATEGORY=${SMOKE_PAIR_PERT_CATEGORY:-Camera Viewpoints}
SMOKE_PAIR_PERT_TASK=${SMOKE_PAIR_PERT_TASK:-${SMOKE_PAIR_BASE_TASK}_view_50_0_100_0_0_initstate_0}
SMOKE_T5_FALLBACK_TO_BASE=${SMOKE_T5_FALLBACK_TO_BASE:-true}
SMOKE_T5_EXTRA_EMBEDDINGS=${SMOKE_T5_EXTRA_EMBEDDINGS:-}
SMOKE_T5_ALLOW_STRICT_COMPUTE=${SMOKE_T5_ALLOW_STRICT_COMPUTE:-false}
SMOKE_LATENT_ADAPTER=${SMOKE_LATENT_ADAPTER:-}
SMOKE_DATA_COLLECTION=${SMOKE_DATA_COLLECTION:-}
SMOKE_HF_HUB_OFFLINE=${SMOKE_HF_HUB_OFFLINE:-1}
SMOKE_PYTHON_SCRIPT=${SMOKE_PYTHON_SCRIPT:-$REPO_ROOT/run_libero_smoke_test.py}

if [ ! -f "$BASE_MODEL_DIR/model-480p-16fps.pt" ]; then
    echo "Missing base checkpoint: $BASE_MODEL_DIR/model-480p-16fps.pt" >&2
    exit 1
fi

if [ ! -f "$BASE_MODEL_DIR/tokenizer/tokenizer.pth" ]; then
    echo "Missing tokenizer checkpoint: $BASE_MODEL_DIR/tokenizer/tokenizer.pth" >&2
    exit 1
fi

if [ ! -f "$POLICY_CKPT_PATH" ] && [ ! -f "$POLICY_CKPT_PATH/.metadata" ]; then
    echo "Missing policy checkpoint: $POLICY_CKPT_PATH" >&2
    exit 1
fi

# Populate the Hugging Face cache layout expected by the hard-coded base-model URI.
mkdir -p "$HF_REPO_DIR/refs" "$HF_REPO_DIR/snapshots"
printf '%s' "$HF_REVISION" > "$HF_REPO_DIR/refs/main"
ln -sfnT "$BASE_MODEL_DIR" "$HF_REPO_DIR/snapshots/$HF_REVISION"

mkdir -p "${TMPDIR:-/tmp}/cosmospolicy-numba" "${TMPDIR:-/tmp}/cosmospolicy-matplotlib"

cd "$REPO_ROOT"

export CUDA_VISIBLE_DEVICES="$GPU_ID"
export MUJOCO_GL="$SMOKE_GL_BACKEND"
export PYOPENGL_PLATFORM="$SMOKE_GL_BACKEND"
export PYTHONNOUSERSITE=1
export PYTHONDONTWRITEBYTECODE=1
export PYTHONPATH="../../LIBERO-plus${PYTHONPATH:+:$PYTHONPATH}"
export NUMBA_CACHE_DIR="${TMPDIR:-/tmp}/cosmospolicy-numba"
export MPLCONFIGDIR="${TMPDIR:-/tmp}/cosmospolicy-matplotlib"
export HF_HUB_CACHE="$CHECKPOINT_ROOT/huggingface-hub"
export HF_HUB_OFFLINE="$SMOKE_HF_HUB_OFFLINE"
export PYTHONHASHSEED="$SMOKE_SEED"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
export TOKENIZERS_PARALLELISM=false

export COSMOS_SMOKE_SUITE="$SMOKE_SUITE"
export COSMOS_SMOKE_TASK_ID="$SMOKE_TASK_ID"
export COSMOS_SMOKE_FLIP_IMAGES="$FLIP_IMAGES"
export COSMOS_POLICY_MODEL_DIR="$POLICY_MODEL_DIR"
export COSMOS_POLICY_CKPT_PATH="$POLICY_CKPT_PATH"
export COSMOS_SMOKE_MODE="$SMOKE_MODE"
export COSMOS_SMOKE_ONLY_CONDITION="$SMOKE_ONLY_CONDITION"
export COSMOS_SMOKE_NUM_PAIRS="$SMOKE_NUM_PAIRS"
export COSMOS_SMOKE_RESULTS_DIR="$SMOKE_RESULTS_DIR"
export COSMOS_SMOKE_RUN_ID="$SMOKE_RUN_ID"
export COSMOS_SMOKE_QUIET_STEP_LOGS="$SMOKE_QUIET_STEP_LOGS"
export COSMOS_SMOKE_PROMPT_OVERRIDE="$SMOKE_PROMPT_OVERRIDE"
export COSMOS_SMOKE_SEED="$SMOKE_SEED"
export COSMOS_SMOKE_DETERMINISTIC_RESET="$SMOKE_DETERMINISTIC_RESET"
export COSMOS_SMOKE_DETERMINISTIC_RESET_SEED="$SMOKE_DETERMINISTIC_RESET_SEED"
export COSMOS_SMOKE_PAIR_SUITE="$SMOKE_PAIR_SUITE"
export COSMOS_SMOKE_PAIR_BASE_TASK="$SMOKE_PAIR_BASE_TASK"
export COSMOS_SMOKE_PAIR_CLEAN_LANGUAGE="$SMOKE_PAIR_CLEAN_LANGUAGE"
export COSMOS_SMOKE_PAIR_PERT_NAME="$SMOKE_PAIR_PERT_NAME"
export COSMOS_SMOKE_PAIR_PERT_CATEGORY="$SMOKE_PAIR_PERT_CATEGORY"
export COSMOS_SMOKE_PAIR_PERT_TASK="$SMOKE_PAIR_PERT_TASK"
export COSMOS_SMOKE_T5_FALLBACK_TO_BASE="$SMOKE_T5_FALLBACK_TO_BASE"
export COSMOS_SMOKE_T5_EXTRA_EMBEDDINGS="$SMOKE_T5_EXTRA_EMBEDDINGS"
export COSMOS_SMOKE_T5_ALLOW_STRICT_COMPUTE="$SMOKE_T5_ALLOW_STRICT_COMPUTE"
export COSMOS_SMOKE_LATENT_ADAPTER="$SMOKE_LATENT_ADAPTER"
export COSMOS_DATA_COLLECTION="$SMOKE_DATA_COLLECTION"

if [ ! -f "$SMOKE_PYTHON_SCRIPT" ]; then
    echo "Missing smoke-test Python program: $SMOKE_PYTHON_SCRIPT" >&2
    exit 1
fi

exec python "$SMOKE_PYTHON_SCRIPT"
