#!/bin/sh

set -eu

REPO_ROOT=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
TASK=${LIBERO10_TASK:-KITCHEN_SCENE4_put_the_black_bowl_in_the_bottom_drawer_of_the_cabinet_and_close_it}
LANGUAGE=${LIBERO10_LANGUAGE:-put the black bowl in the bottom drawer of the cabinet and close it}
NUM_CASES=${NUM_CASES:-1}
SEED=${SEED:-0}
SMOKE_PYTHON_SCRIPT=${SMOKE_PYTHON_SCRIPT:-$REPO_ROOT/run_libero_smoke_test.py}
ROBOTINIT_GPU=${ROBOTINIT_GPU:-2}
OUTPUT_ROOT=${OUTPUT_ROOT:-$REPO_ROOT/experiments/libero10_robotinit_single}
COSMOS_ROLLOUT_SUBDIR=${COSMOS_ROLLOUT_SUBDIR:-08-17}

# --- Data collection (save trajectory HDF5 for offline analysis) ---
COSMOS_DATA_COLLECTION=${COSMOS_DATA_COLLECTION:-}
# --- Vector DB (save VAE latents + proprio at action chunk boundaries) ---
COSMOS_VECTOR_DB=${COSMOS_VECTOR_DB:-}
COSMOS_VECTOR_DB_DIR=${COSMOS_VECTOR_DB_DIR:-}
# --- Phase verifier + retrieval-based phase recovery ---
COSMOS_PHASE_VERIFIER=${COSMOS_PHASE_VERIFIER:-1}
COSMOS_PHASE_RECOVERY=${COSMOS_PHASE_RECOVERY:-1}
COSMOS_FEASIBLE_RECOVERY=${COSMOS_FEASIBLE_RECOVERY:-0}
# --- Init state offset (default 0 = first init state) ---
# Episode N = init_state_index N-1. Set OFFSET=2 for episode 3.
COSMOS_INIT_STATE_OFFSET=${COSMOS_INIT_STATE_OFFSET:-4}

# --- Robot init state (default 274) ---
ROBOTINIT_STATE=${ROBOTINIT_STATE:-274}

RESULT_NAME=robotinit
MODE_NAME=normal

mkdir -p "$OUTPUT_ROOT/$RESULT_NAME" "$OUTPUT_ROOT/tmp-robotinit"

cd "$REPO_ROOT"

# Legacy manual-injection controls are deliberately unsupported.
unset COSMOS_OFFSET_START_T COSMOS_OFFSET_AMOUNT COSMOS_OFFSET_DURATION COSMOS_ONLINE_INJECT

COSMOS_ROLLOUT_SUBDIR="$COSMOS_ROLLOUT_SUBDIR" \
COSMOS_SKIP_PLAIN_ROLLOUT=1 \
COSMOS_INIT_STATE_OFFSET="$COSMOS_INIT_STATE_OFFSET" \
SMOKE_DATA_COLLECTION="$COSMOS_DATA_COLLECTION" \
COSMOS_VECTOR_DB="$COSMOS_VECTOR_DB" \
COSMOS_VECTOR_DB_DIR="$COSMOS_VECTOR_DB_DIR" \
COSMOS_PHASE_VERIFIER="$COSMOS_PHASE_VERIFIER" \
COSMOS_PHASE_RECOVERY="$COSMOS_PHASE_RECOVERY" \
COSMOS_FEASIBLE_RECOVERY="$COSMOS_FEASIBLE_RECOVERY" \
TMPDIR="$OUTPUT_ROOT/tmp-robotinit" \
SMOKE_PYTHON_SCRIPT="$SMOKE_PYTHON_SCRIPT" \
GPU_ID="$ROBOTINIT_GPU" \
SMOKE_GL_BACKEND=egl \
SMOKE_ONLY_CONDITION=perturb \
SMOKE_PAIR_SUITE=libero_10 \
SMOKE_PAIR_BASE_TASK="$TASK" \
SMOKE_PAIR_CLEAN_LANGUAGE="$LANGUAGE" \
SMOKE_PAIR_PERT_NAME=robot_initial_states \
SMOKE_PAIR_PERT_CATEGORY="Robot Initial States" \
SMOKE_PAIR_PERT_TASK="${TASK}_view_0_0_100_0_0_initstate_${ROBOTINIT_STATE}" \
SMOKE_NUM_PAIRS="$NUM_CASES" \
SMOKE_SEED="$SEED" \
SMOKE_RESULTS_DIR="$OUTPUT_ROOT/$RESULT_NAME" \
SMOKE_RUN_ID="robotinit_single_${MODE_NAME}_gpu${ROBOTINIT_GPU}" \
sh ./run_libero_smoke_test.sh
# echo "Robotinit single case evaluation complete: $OUTPUT_ROOT"
